name: Run Tests

on:
  push:
    tags:
      - '!releases/[1-9]+.[0-9]+.[0-9]+'
    branches: 
      - '**'
      - '!develop'
      - '!main'

jobs:
  install:
    name: Static and UnitTests in all branches
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.13.1'
    - name: NPM install
      run: |
        npm install
        npm run build
    - name: NPM Test
      run: |
        npm test
    - name: Run E2E Testing
      run: |
        # npm run test:e2e
    - name: Run coverage
      run: |
        npm run test:cov
        

